### ISSUE TITLE
Im Frontend deaktivierbar

### ISSUE THREAD

**Issue by polarpixel** [olien/rexpixel#10]
Nicht wichtig, aber eine kleine Idee:
Es wäre ganz nett, wenn man die Anzeige des Layers im Frotend mal rasch deaktivieren könnte.
Sicher, man kann die Transparenz auf 0 setzen und das in den Hintergrund setzen, damit Links klickbar sind, aber vielleicht wäre eine Checkbox für aktiv / inaktiv besser.

**Comment by olien** [comment]
ok

**Comment by olien** [comment]
Funktioniert schon. Wird aber noch nicht gespeichert und beim Reload nicht berücksichtigt...

**Comment by olien** [comment]
Erledigt. Der Status wird jetzt ausgewertet beim reload.
