### ISSUE TITLE
Alternative: Handling der Vorlagen

### ISSUE THREAD

**Issue by polarpixel** [olien/rexpixel#11]
Wie Du es jetzt gemacht (Medienlist-Feld) und man wählt im Frontend die jeweils benötigte Vorlage), kann man es gut verwenden.
Wollt Dir dennoch eben sagen, wie ich es vermutlich aufgezogen hätte:
Da wir ja immer eine gewisse Zahl an Vorlagen bekommen und dann entsprechende Musterseiten bauen, hätte ich die Vorlagen eher an Artikel geknüpft. Sprich: Ein Datensatz besteht aus Link-Button und Media-Button. So kann man z.B. gleich der Kontaktseite den Kontakt-Screenshot fest zuweisen, etc. und muss nicht im Frontend hin und her klicken.

Ist halt ein anderer Ansatz, kannst Du einfach zur Kenntnis nehmen und dann hier schließen.

**Comment by olien** [comment]
Das ist eine gute Idee. Habe auch schon überlegt ob die die Vorlagen im Forntend pixelganu positionierbar machen. Dann müsste ich zu jedem Bild die Positionsdaten speichern. 
Macht das Sinn oder wäre das zu aufwändig?

Mir reicht rechts, links, mitte...

Was meinst du?

LG
Oliver

**Comment by polarpixel** [comment]
Das reicht mir auch, denn oben wird man ja eh immer 0px haben und je nach Layout eben links 0, rechts 0 oder eben zentriert.

**Comment by olien** [comment]
Bei deinem Vorschlag müsste ich aber eine feste Anzahl von möglichen Bildern vorgeben - oder?

Ausserdem kann es für einen Artikel noch mehrere Bilder geben (Stichwort RWD)

Ich dachte eher, dass man mit einem Satz Bilder eine Seite (Startseite, Kontaktseite) mit unterschiedlichen Vorlagen entwickelt. 

Dann wäre ein Datensatz = Artikellink + Medialist... Ist das noch sinnvoll?

**Comment by polarpixel** [comment]
Responsive ist ein gutes Stichwort, da hast Du recht. Dann wäre es aber natürlich gut, wenn man min-width und max-width für eine Vorlage hinterlegen kann. Hier käme dann doch wieder meine Idee zum Tragen, denn ich meinte, dass man beliebig viele Datensätze anlegen kann.
Ein Datensatz würde dann bestehen aus Medialist, Linklist und Text- oder Textarea-Feld(ern), wo man die Media Queries eintragen kann. Wenn man es komfortabel machen will, kann man es ja so machen, dass eine Handvoll Felder hat, wo man jeweils eine Zahl einträgt und dann jeweils ein Selectfeld hat, wo man min-width doer max-with etc. auswählen kann. Muss aber nicht sein - ein Textareafeld wo man optional die Media Query reinschreibt, würde ja ausreichen.

Aber wie gesagt: Das ist ein etwas anderer Ansatz, der sicher größeren Umbau erfordert und eher Geschmackssache ist. Das hier wäre viel wichtiger:
https://github.com/olien/rexpixel/issues/12

**Comment by olien** [comment]
Ich konzentriere mich mal auf Issue #12   :-)
