### ISSUE TITLE
Vorlage muss mitscrollen

### ISSUE THREAD

**Issue by polarpixel** [olien/rexpixel#12]
Es gibt Layouts, die länger sind als unsere Bildschirmhöhe. Deswegen müsste beim Scrollen die Vorlage mitscrollen und nicht fix stehen.
Warum hast Du #rexpixel auf fixed stehen statt auf absolute, was mir sinnvoller erscheinen würde?

**Comment by polarpixel** [comment]
Habs grade mal ausprobiert: Zusätzlich zu absolute müsste die Höhe von #rexpixel auch als min-height die Höhe des ausgewählten Bildes bekommen, damit das nutzbar ist.

**Comment by olien** [comment]
ok. berücksichtige ich. danke!

**Comment by polarpixel** [comment]
Habs heute mal getestet: Mit height-Wert und pos:abs ist es noch nicht ganz getan, denn wenn man weiter nach unten gescrollt das Bild verschiebt, klappt das derzeit nicht, der Bezugspunkt dafür ist anscheinend oben. Teste einfach mal eine 3000px hohe Vorlage, dann siehst Du die Haken, die es da derzeit noch gibt.

**Comment by olien** [comment]
Guck doch mal bitte ob es jetzt wie gewünscht funktioniert.

**Comment by polarpixel** [comment]
Ja, es scheint zu funktionieren. Super, das ist jetzt echt praktisch.

Allerdings habe ich den Eindruck, dass es jetzt beim Wechseln des Bildes etwas "hakelt". Man muss manchmal mehrmals hin und her klicken, bis das Bild angezeigt wird. Gib mir noch 1 oder 2 Tage, um das ausführlicher zu probieren.

**Comment by olien** [comment]
Ok. 100% getestet habe ich es auch noch nicht. Sind ja auch noch ein paar issues offen :-)

## 

Via Handy

**Comment by olien** [comment]
So. Jetzt würde ich dich bitte das nochmal zu testen. Design bitte ignorieren :-)

**Comment by polarpixel** [comment]
Klappt jetzt. Danke!
