### ISSUE TITLE
Bedienung "z-index" und "Layoutvorlage deaktivieren" nicht möglich

### ISSUE THREAD

**Issue by medienschmiede71** [olien/rexpixel#17]
Im Chrome und Safari ist die Bedienung der beiden Elemente nicht möglich. 

Zwar hatte ich gelesen, dass Du die Optik erst später machst, das geht aber doch schon in die Funktionalität über ;)
![bildschirmfoto 2013-12-12 um 01 16 02](https://f.cloud.github.com/assets/6106333/1729576/b70b8160-62c3-11e3-8db5-d1960502daa9.png)

Cheers,
Marc

**Comment by olien** [comment]
Danke sehr. Gucke ich mir an!

**Comment by olien** [comment]
Ich habe es jetzt kurz in den aktuellen Versionen von Chrome, Safari, Aurora und Opera getestet (Mac).
Funktioniert alles. (Auch wenns nicht schön aussieht).

Kannst Du mir mal Betriebssystem und Browserversion mitteilen oder mal kurz gucken ob du etwas findest?

LG
OLiver

**Comment by medienschmiede71** [comment]
Das Problem liegt am CSS der eigentlichen Website. In meinem Falle findet sich dort im CSS die Anweisung "-webkit-appearance: none;", welche dann auch auf das Widget greift. Deaktiviere ich diese, dann erscheinen auch die Checkboxen.

Cheers,
Marc

**Comment by olien** [comment]
Hey Marc,

meinst du das muss ich berücksichtigen oder kann ich das ignorieren?

LG
Oliver

**Comment by medienschmiede71** [comment]
Ignorieren +1

Du kannst das "umgebende" CSS ja nicht vorhersehen.

**Comment by olien** [comment]
Ja. Und wenn ich das aushebel macht das Tool ja keinen sinn mehr :-))

Danke!
