### ISSUE TITLE
Vorlagen per drag & drop verschiebbar machen

### ISSUE THREAD

**Issue by olien** [olien/rexpixel#2]
Layer muss dann höchten z-index haben

**Comment by polarpixel** [comment]
Genau das wollte ich auch schreiben, fände ich sehr wichtig.
Ggf. in Kombination mit dieser Option:
https://github.com/olien/rexpixel/issues/8

**Comment by olien** [comment]
Erledigt

**Comment by polarpixel** [comment]
Sehr schön, danke.
