### ISSUE TITLE
Idee: responsive

### ISSUE THREAD

**Issue by Sysix** [olien/rexpixel#20]
Hey erstmals coole Idee fürs addon.
Würde ich net mit bootstrap arbeiten (was nervig ist in Photoshop nachzubauen) hat ich bestimmt viel Spaß am addon, da mich es mich zu meinen Anfangszeiten genervt hat immer am Bildschirm zu glotzen ob wirklich es pixelgenau ist ;)

Aber nun zur meiner Idee:

Da man nach den mobile first Prinzip gehen sollte (auch in ps) würde eine ein multiple fileupload net schaden, wo das Bild bei der bildschrim breite sich automatisch anpasst (JS)

Vielleicht siehst du es genauso:)

Gruß sysix

**Comment by olien** [comment]
Hey Alexander,

danke für dein Input. Ich glaube ja fast, dass das Addon seine Berechtigung eher vor einigen Jahren gehabt hätte. Wer bei einer responsiven Webseite Pixel kontrolliert... naja...

Ich glaub nicht wirklich das der Aufwand sich lohnt. Jetzt kannst du ja schon mehrere Bilder nutzen. 
Ich würde dann evtl. drei (oder mehr) Vorlagen (je nach Breakpoints) hochladen und händisch umschalten.

Wie würdest du die Idee denn umsetzten? Eine Checkbox  "Responsive Anzeige ja / nein) und dann eine Textfeld für die Breakpoints? Sollte dann geprüft werden ob die Anzahl der Bilder der Anzahl der Breakpoints entspricht? Oder die Breakpoints an den Dateinamen festmachen (320.jpg, 720.jpg...)

Würdest Du damit arbeiten? Ich glaube ich nicht.... Bin aber offen für eine weitere Diskussion!
LG
Oliver

**Comment by Sysix** [comment]
Ich schließ das Ticket, ist nichtmehr Zeitgemäß
