### ISSUE TITLE
Kleiner Darstellungsfehler

### ISSUE THREAD

**Issue by polarpixel** [olien/rexpixel#9]
im Crome: Label und Felder teils verrutscht.
![ad-verbum home 2013-12-02 09-11-35](https://f.cloud.github.com/assets/330160/1653093/5f609cb2-5b29-11e3-9b82-2714dbd15e21.png)

Den Begriff "z-index ändern" fand ich missverständlich, ich muss immer noch nachdenken, wenn ich es ändere.
Besser:

z-index der Vorlage
[] unten
[] oben

**Comment by olien** [comment]
Gute Idee. 

Frontend "Design" habe ich eigentlich noch gar nicht gemacht.
Ich möchte erst die Funktionen fertig haben.

LG 
Oliver

**Comment by polarpixel** [comment]
Dachte ich auch schon so. Wollte es nur durchgeben.

**Comment by olien** [comment]
:-)

**Comment by olien** [comment]
Design machen wir (ich) später :-)
